[build-system]
    requires = ["setuptools>=68", "wheel"]
    build-backend = "setuptools.build_meta"

[project]
    name = "npc-maker"
    version = "0.4.0"
    requires-python = ">=3.12"
    readme = "README.md"
    license = "MIT-0"
    authors = [
        { name = "David McDougall", email = "dam1784@rit.edu" },
    ]
    description = "Evolve AIs in simulated environments"
    keywords = ["Evolution", "Artificial-Life", "AI", "npc_maker"]
    classifiers = [
        "Natural Language :: English",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Life",
    ]
    dependencies = []

[project.urls]
    Repository = "https://github.com/D-McDougall/npc_maker"

[project.scripts]
    "npc-maker.py" = "npc_maker.programs.npc_maker:main"
    npc-player     = "npc_maker.programs.npc_player:main"
    npc-evo        = "npc_maker.programs._launcher:npc_evo"
    npc-maker      = "npc_maker.programs._launcher:npc_maker"

[tool.setuptools.packages.find]
    where = ["python"]
    exclude = ["tests"]
    namespaces = false

[tool.setuptools.package-data]
    npc_maker = ["programs/*"]
