syntax = "proto3";

import "individual.proto";

package environment;

/*
An environment program is self-contained simulated world. The `npc-server`
program connects Environment programs to Evolution and Genetics services via
the Environment service.
*/
service Environment {

  /*
  Request a new individual from the evolutionary algorithm
  */
  rpc Spawn(SpawnRequest) returns (individual.Individual);

  /*
  Request a new individual by mating individuals together. This requires at
  least one parent. This accepts more than two parents. All parents must be
  alive, in this environment, and having the same body_type
  */
  rpc Mate(MateRequest) returns (individual.Individual);

  /*
  Report the reproductive fitness of a living individual.
  This overwrites any previously reported value.
  */
  rpc Score(ScoreRequest) returns (ScoreResponse);

  /*
  The environment associates some extra information with a living individual.
  The info is kept alongside the individual in perpetuity.
  */
  rpc Telemetry(TelemetryRequest) returns (TelemetryResponse);

  /*
  */
  rpc Epigenome(EpigenomeRequest) returns (EpigenomeResponse);

  /*
  Report the death of an individual.
  */
  rpc Death(DeathRequest) returns (DeathResponse);
}

message SpawnRequest {
  /*
  Corresponds to an organism name in the experiment specification
  */
  string body_type = 1;
}

message MateRequest {
  /*
  Argument parents is a list of individual's names.
  */
  repeated string parents = 1;
}

/*
Update the reproductive fitness of a living individual.
*/
message ScoreRequest {
  /*
  Individual's name. The Individual must be alive and in this instance of the
  environment, meaning that its final score must be reported _before_ the death
  is called on the Individual.
  */
  string name = 1;

  double score = 2;
}

message ScoreResponse {
}

/*
Set or update the environmential telemetry for an individual.

Every indvidual has an associative key-value store for the metadata it
accumulates over the course of its lifetime.
*/
message TelemetryRequest {
  /*
  Individual's name. Individual must be alive and in this instance of the
  environment.
  */
  string name = 1;

  repeated KeyValue data = 2;
}

message TelemetryResponse {
}

message EpigenomeRequest {
  string name = 1;
  bytes data = 2;
}

message EpigenomeResponse {
}

/*
*/
message KeyValue {
  string key = 1;
  string value = 2;
}

/*
Notifies the npc-server and evolutionary algorithm that an individual has exited
the environment.
*/
message DeathRequest {
  /*
  Name of the deceased Individual.
  */
  string name = 1;
}

message DeathResponse {
}
