syntax = "proto3";

import "individual.proto";

package environment;

service Environment {
  rpc Spawn(SpawnRequest) returns (individual.Individual);
  rpc Mate(MateRequest) returns (individual.Individual);
  rpc Score(ScoreRequest) returns (ScoreResponse);
  rpc Telemetry(TelemetryRequest) returns (TelemetryResponse);
  rpc Epigenome(EpigenomeRequest) returns (EpigenomeResponse);
  rpc Death(DeathRequest) returns (DeathResponse);
}

message SpawnRequest {
  string body_type = 1;
}

message MateRequest {
  /*
  Argument parents is a list of individual's names.
  */
  repeated string parents = 1;
}

message ScoreRequest {
  string name = 1;
  double score = 2;
}

// Empty
message ScoreResponse {
}

/*
*/
message KeyValue {
  string key = 1;
  string value = 2;
}

message TelemetryRequest {
  string name = 1;
  repeated KeyValue data = 2;
}

// Empty
message TelemetryResponse {
}

message EpigenomeRequest {
  string name = 1;
  repeated KeyValue data = 2;
}

// Empty
message EpigenomeResponse {
}

/*
Notifies the evolutionary algorithm that an individual has exited the environment.
*/
message DeathRequest {
  string name = 1;
}

// Empty
message DeathResponse {
}
