syntax = "proto3";

package env;

service Environment {
  rpc Spawn(SpawnRequest) returns (Child);
  rpc Mate(MateRequest) returns (Child);
  rpc Score(ScoreRequest) returns (ScoreResponse);
  rpc Telemetry(TelemetryRequest) returns (TelemetryResponse);
  rpc Death(DeathRequest) returns (DeathResponse);
}

message SpawnRequest {
  string body_type = 1;
}

message MateRequest {
  /*
  Argument parents is a list of individual's names.
  */
  repeated string parents = 1;
}

/*
Child represents a new individual entering the environment.
*/
message Child {
  string name = 1;
  string body_type = 2;
  repeated string parents = 3;
  repeated string controller = 4;
  bytes phenome = 5;
}

message ScoreRequest {
  string name = 1;
  double score = 2;
}

// Empty
message ScoreResponse {
}

message TelemetryRequest {
  string name = 1;
  repeated KeyValue data = 2;
}

message KeyValue {
  string key = 1;
  string value = 2;
}

// Empty
message TelemetryResponse {
}

/*
Notifies the evolutionary algorithm that an individual has exited the environment.
*/
message DeathRequest {
  string name = 1;
}

// Empty
message DeathResponse {
}
