syntax = "proto3";

import "individual.proto";

package evolution;

/*
The purpose of the evolution service is to maintain a population of
individuals and to pick which individuals should reproduce.
*/
service Evolution {
  /*
  Request parents for making a new individual

  This may return any number of Individuals. If the Evolution service returns
  zero individuals then use the initial genetic material.
  */
  rpc Spawn(SpawnRequest) returns (SpawnResponse);

  /*
  Notify the Evolution service that an Individual has died
  */
  rpc Death(DeathRequest) returns (DeathResponse);
}

// Empty
message SpawnRequest {
}

message SpawnResponse {
  repeated individual.Individual parents = 1;
}

message DeathRequest {
  individual.Individual individual = 1;
}

// Empty
message DeathResponse {
}
