syntax = "proto3";

package experiment;

/*
Format for JSON experiment files (*.exp).

The experiment message defines the semantics of a complete artificial-life
experiment.
*/
message Experiment {

  string name = 1;

  string description = 2;

  /*
  Command line invocation for the environment program
  */
  repeated string environment = 3;

  /*
  Default evolution service (command line invocation)
  */
  repeated string evolution = 4;

  /*
  Default genetics service (command line invocation)
  */
  repeated string genetics = 5;

  /*
  Default controller service (command line invocation)
  */
  repeated string controller = 6;

  repeated Organism organisms = 7;
}

/*
Organism messages attach a evolutionary algorithm, genetic algorithm, and
control system to each body type.
*/
message Organism {

  string body_type = 1;

  optional string description = 2;

  /*
  Command line invocation for this organism's Evolution service.

  If missing then all spawn requests will create founder individuals, by sending
  zero parents to the genetic service.

  Each instance of the Evolution service is assigned a subdirectory in the
  persistence_directory, which it uses as its initial working directory.
  */
  repeated string evolution = 3;

  /*
  Command line invocation for this organism's Genetics service.

  If missing then the npc-server will use the first parent's genetic material,
  as returned by the evolution service.

  Each instance of the Genetics service is assigned a subdirectory in the
  persistence_directory, which it uses as its initial working directory.
  */
  repeated string genetics = 4;

  /*
  Command line invocation for this organism's Controller service.
  */
  repeated string controller = 5;
}
