syntax = "proto3";

import "individual.proto";

package genetics;

/*

The word "**genome**" refers to a complete
set of parameters for creating an AI agent's control system. Each individual
has exactly one immutable genome

Genomes are treated as opaque binary objects outside of genetic algorithms.
Genomes are converted into "**phenomes**" before transmission to controllers.
This decouples the genetic representation from the control system implementation.

*/
service Genetics {
  /*
  */
  rpc Reproduce(ReproduceRequest) returns (ReproduceResponse);
}

/*
List parent Individuals

Each parent must have a genome
*/
message ReproduceRequest {
  repeated individual.Individual parents = 1;
}

/*
*/
message ReproduceResponse {
  individual.Individual child = 1;
}
