syntax = "proto3";

package individual;

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

/*
Individuals are the entities that evolve

The file format for an individual consists of a directory named after the
individual's name, located beneath the directory supplied to `save()`. The
directory contains four files: metadata.json, which contains the individual's
metadata serialized using the protobuf JSON mapping, and genome, epigenome,
and phenome, which contain the corresponding data as raw binary.
*/
message Individual {
  Metadata metadata = 1;
  optional bytes genome = 2;
  optional bytes epigenome = 3;
  optional bytes phenome = 4;
}

/*
Metadata for an Individual
*/
message Metadata {
  /*
  UUID of this individual

  Typically, this will be a 128 bit random number as 32 uppercase hex digits
  (UUID-4), but technically it can be any string that us universally unique
  among all individuals.
  */
  string name = 1 [
    json_name = "name"
  ];

  /*
  Name of the environment that this individual lives in
  */
  optional string environment = 2 [
    json_name = "environment"
  ];

  /*
  Name of the body type used by this individual
  */
  optional string body_type = 3 [
    json_name = "body_type"
  ];

  /*
  Command-line invocation of the controller program
  */
  repeated string controller = 4 [
    json_name = "controller"
  ];

  /*
  Reproductive fitness of this individual, as assessed by the environment
  */
  optional double score = 5 [
    json_name = "score"
  ];

  /*
  Environmental information
  */
  map<string, string> telemetry = 6 [
    json_name = "telemetry"
  ];

  /*
  UUID for artificial speciation
  */
  optional string species = 7 [
    json_name = "species"
  ];

  /*
  Names of parents
  */
  repeated string parents = 8 [
    json_name = "parents"
  ];

  /*
  Number of children
  */
  optional uint64 children = 9 [
    json_name = "children"
  ];

  /*
  Number of generations that came before this individual
  */
  optional uint64 generation = 10 [
    json_name = "generation"
  ];

  /*
  Number of individuals who died before this one
  */
  optional uint64 ascension = 11 [
    json_name = "ascension"
  ];

  /*
  UTC time at which this individual was born
  */
  optional google.protobuf.Timestamp birth_date = 12 [
    json_name = "birth_date"
  ];

  /*
  UTC time at which this individual died
  */
  optional google.protobuf.Timestamp death_date = 13 [
    json_name = "death_date"
  ];

  /*
  User-defined fields are allowed in the `extra` dictionary.
  */
  google.protobuf.Struct extra = 100 [
    json_name = "extra"
  ];
}
