syntax = "proto3";

package individual;

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

/*
Metadata for an Individual

Each individual is a distinct life-form with its own genome.

Evolutionary algorithms operate on individuals, while genetic algorithms
operate on genomes.
*/
message Individual {
  /*
  UUID of this individual
  */
  string name = 1 [
    json_name = "name"
  ];

  /*
  Name of the environment that this individual lives in
  */
  optional string environment = 2 [
    json_name = "environment"
  ];

  /*
  Name of the body type used by this individual
  */
  optional string body_type = 3 [
    json_name = "body_type"
  ];

  /*
  Command-line invocation of the controller program
  */
  repeated string controller = 4 [
    json_name = "controller"
  ];

  /*
  Reproductive fitness of this individual, as assessed by the environment
  */
  optional double score = 5 [
    json_name = "score"
  ];

  /*
  Environmental information
  */
  map<string, string> telemetry = 6 [
    json_name = "telemetry"
  ];

  /*
  UUID for artificial speciation
  */
  optional string species = 7 [
    json_name = "species"
  ];

  /*
  Names of parents
  */
  repeated string parents = 8 [
    json_name = "parents"
  ];

  /*
  Number of children
  */
  optional uint64 children = 9 [
    json_name = "children"
  ];

  /*
  Number of generations that came before this individual
  */
  optional uint64 generation = 10 [
    json_name = "generation"
  ];

  /*
  Number of individuals who died before this one
  */
  optional uint64 ascension = 11 [
    json_name = "ascension"
  ];

  /*
  UTC time at which this individual was born
  */
  optional google.protobuf.Timestamp birth_date = 12 [
    json_name = "birth_date"
  ];

  /*
  UTC time at which this individual died
  */
  optional google.protobuf.Timestamp death_date = 13 [
    json_name = "death_date"
  ];

  /*
  User-defined fields are allowed in the `extra` dictionary.
  */
  google.protobuf.Struct extra = 100 [
    json_name = "extra"
  ];
}
